name: Modified Application Trigger

on:
  push:
    paths:
      - 'software/apps/**'
jobs:
  build:
    name: Run Make in Changed Folders
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: List Changed Folders
        run: |
          echo "Changed Folders:"
          git diff --name-only ${{github.even.before}} ${{github.sha}} | grep '^software/apps/' | cut -d/ -f5 | uniq > changed_folders.txt || true
          cat changed_folders.txt
          
      - name: Run Make in Changed Folders
        run: |
          while IFS=read folder || [ -n "$folder" ]; do
            cd "software/apps/$folder" || exit
            make
            cd - 
          done < changed_folders.txt
